import * as React from 'react';
import { ClipboardDocumentCheckIcon, ClipboardDocumentIcon, ExclamationTriangleIcon } from './icons';

const unifiedScript = `
-- =================================================================
-- السكربت الشامل والنهائي (الإصدار 32.4)
-- =================================================================
-- هذا السكربت يقوم بإعداد قاعدة البيانات بالكامل، تفعيل المزامنة الفورية، وإنشاء حساب مدير تلقائياً.
-- يطبق هذا الإصدار صلاحيات أمان تعاونية تسمح لجميع المستخدمين بالاطلاع على البيانات ومزامنة الوثائق.
-- انسخ هذا السكربت بالكامل وشغّله مرة واحدة فقط في Supabase SQL Editor.
-- !! هام: عدّل رقم هاتف وكلمة مرور المدير في نهاية السكربت قبل التشغيل !!

-- 1. CLEANUP: Drop all existing objects in reverse order of dependency.
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT 'DROP POLICY IF EXISTS "' || policyname || '" ON public.' || tablename || ';' as statement FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE r.statement;
    END LOOP;
END$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.is_admin() CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.delete_user_account() CASCADE;
DROP FUNCTION IF EXISTS public.delete_user(user_id_to_delete uuid) CASCADE;
DROP FUNCTION IF EXISTS public.check_if_mobile_exists(text) CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_at_column() CASCADE;
DROP TABLE IF EXISTS public.site_finances CASCADE;
DROP TABLE IF EXISTS public.case_documents CASCADE;
DROP TABLE IF EXISTS public.invoice_items CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.stages CASCADE;
DROP TABLE IF EXISTS public.cases CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.admin_tasks CASCADE;
DROP TABLE IF EXISTS public.appointments CASCADE;
DROP TABLE IF EXISTS public.accounting_entries CASCADE;
DROP TABLE IF EXISTS public.assistants CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. HELPER & RPC FUNCTIONS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role INTO user_role FROM public.profiles WHERE id = auth.uid();
    RETURN COALESCE(user_role, 'user') = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;

CREATE OR REPLACE FUNCTION public.delete_user_account()
RETURNS void AS $$
BEGIN
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;
GRANT EXECUTE ON FUNCTION public.delete_user_account() TO authenticated;

CREATE OR REPLACE FUNCTION public.delete_user(user_id_to_delete uuid)
RETURNS void AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Only admins can delete users.';
    END IF;
    IF auth.uid() = user_id_to_delete THEN
        RAISE EXCEPTION 'Admins cannot delete their own account from the admin panel.';
    END IF;
    DELETE FROM auth.users WHERE id = user_id_to_delete;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;
GRANT EXECUTE ON FUNCTION public.delete_user(user_id_to_delete uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.check_if_mobile_exists(mobile_to_check text)
RETURNS boolean AS $$
DECLARE
    mobile_exists boolean;
    normalized_check_text text := '0' || RIGHT(regexp_replace(mobile_to_check, '\\D', '', 'g'), 9);
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM public.profiles 
        WHERE '0' || RIGHT(regexp_replace(mobile_number, '\\D', '', 'g'), 9) = normalized_check_text
    ) INTO mobile_exists;
    RETURN mobile_exists;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
GRANT EXECUTE ON FUNCTION public.check_if_mobile_exists(text) TO anon, authenticated;


-- 3. TABLES CREATION
CREATE TABLE public.profiles (id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, full_name text, mobile_number text UNIQUE, is_approved boolean DEFAULT false, is_active boolean DEFAULT true, subscription_start_date date, subscription_end_date date, role text DEFAULT 'user', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), admin_tasks_layout text DEFAULT 'vertical');
CREATE TABLE public.assistants (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL, UNIQUE(user_id, name));
CREATE TABLE public.clients (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL, contact_info text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.cases (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, client_id text NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE, subject text NOT NULL, client_name text, opponent_name text, fee_agreement text, status text DEFAULT 'active', updated_at timestamptz DEFAULT now());
CREATE TABLE public.stages (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, case_id text NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE, court text NOT NULL, case_number text, first_session_date timestamptz, decision_date timestamptz, decision_number text, decision_summary text, decision_notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.sessions (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, stage_id text NOT NULL REFERENCES public.stages(id) ON DELETE CASCADE, court text, case_number text, date timestamptz NOT NULL, client_name text, opponent_name text, postponement_reason text, next_postponement_reason text, is_postponed boolean DEFAULT false, next_session_date timestamptz, assignee text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.admin_tasks (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, task text NOT NULL, due_date timestamptz NOT NULL, completed boolean DEFAULT false, importance text DEFAULT 'normal', assignee text, location text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.appointments (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title text NOT NULL, "time" text, date timestamptz NOT NULL, importance text, notified boolean, reminder_time_in_minutes integer, assignee text, completed boolean DEFAULT false, updated_at timestamptz DEFAULT now());
CREATE TABLE public.accounting_entries (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, type text NOT NULL, amount real NOT NULL, date timestamptz NOT NULL, description text, client_id text, case_id text, client_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.invoices (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, client_id text NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE, client_name text, case_id text REFERENCES public.cases(id) ON DELETE SET NULL, case_subject text, issue_date timestamptz NOT NULL, due_date timestamptz NOT NULL, tax_rate real DEFAULT 0, discount real DEFAULT 0, status text DEFAULT 'draft', notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.invoice_items (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, invoice_id text NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE, description text NOT NULL, amount real NOT NULL, updated_at timestamptz DEFAULT now());
CREATE TABLE public.site_finances (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, type text DEFAULT 'income' NOT NULL, payment_date date NOT NULL, amount real NOT NULL, description text, payment_method text, category text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.case_documents (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, case_id text NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE, name text NOT NULL, type text NOT NULL, size real NOT NULL, added_at timestamptz DEFAULT now() NOT NULL, storage_path text, updated_at timestamptz DEFAULT now());


-- 4. AUTOMATION: Trigger function for new user signup.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- Bypassing RLS for this specific operation inside a security definer function.
  -- This is safe as it's confined to this trigger. The setting is transaction-scoped.
  PERFORM set_config('rls.bypass_rls', 'on', true);

  INSERT INTO public.profiles (id, full_name, mobile_number, created_at)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'mobile_number',
    new.created_at
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    mobile_number = EXCLUDED.mobile_number,
    created_at = EXCLUDED.created_at;
  
  UPDATE auth.users SET email_confirmed_at = NOW() WHERE id = new.id;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;


CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. SECURITY: RLS POLICIES (COLLABORATIVE MODEL)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounting_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_finances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies for the 'profiles' table (special case).
DROP POLICY IF EXISTS "Users can manage their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can create and manage their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Admins can manage all profiles." ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can view all profiles." ON public.profiles;

CREATE POLICY "Authenticated users can view all profiles." ON public.profiles FOR SELECT
  USING (auth.role() = 'authenticated');
  
CREATE POLICY "Users can create and manage their own profile." ON public.profiles FOR ALL
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Admins can manage all profiles." ON public.profiles FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- RLS policies for all other user-specific tables.
DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'assistants', 'clients', 'cases', 'stages', 'sessions', 
        'admin_tasks', 'appointments', 'accounting_entries', 
        'invoices', 'invoice_items', 'case_documents', 'site_finances'
    ]
    LOOP
        -- Clean up all possible old policy names.
        EXECUTE format('DROP POLICY IF EXISTS "Users can manage their own data" ON public.%I;', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Admins can manage all data" ON public.%I;', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Authenticated users can view all data" ON public.%I;', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Users can modify their own data" ON public.%I;', table_name);

        -- 1. Any authenticated user can read any data in the table.
        EXECUTE format('
            CREATE POLICY "Authenticated users can view all data" ON public.%I FOR SELECT
            USING (auth.role() = ''authenticated'');
        ', table_name);

        -- 2. Users can only insert, update, or delete their own data.
        EXECUTE format('
            CREATE POLICY "Users can modify their own data" ON public.%I FOR INSERT, UPDATE, DELETE
            USING (auth.uid() = user_id)
            WITH CHECK (auth.uid() = user_id);
        ', table_name);

        -- 3. Admins get full unrestricted access (this combines with the above policies via OR logic).
        EXECUTE format('
            CREATE POLICY "Admins can manage all data" ON public.%I FOR ALL
            USING (public.is_admin())
            WITH CHECK (public.is_admin());
        ', table_name);
    END LOOP;
END$$;

-- 6. REALTIME: Enable real-time updates for all user data tables idempotently.
DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'profiles', 'assistants', 'clients', 'cases', 'stages', 'sessions', 
        'admin_tasks', 'appointments', 'accounting_entries', 'invoices', 
        'invoice_items', 'site_finances', 'case_documents'
    ]
    LOOP
        -- Add the table to the publication only if it's not already there
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND tablename = table_name AND schemaname = 'public'
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I;', table_name);
        END IF;
    END LOOP;
END$$;

-- 7. PERMISSIONS
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =================================================================
-- 8. إنشاء حساب المدير تلقائياً وتصحيحه
-- =================================================================
-- !! هام: عدّل البيانات التالية قبل تشغيل السكربت !!
DO $$
DECLARE
    admin_phone_local TEXT := '0987654321'; -- <-- غيّر رقم هاتف المدير هنا
    admin_phone_no_plus TEXT := '963' || RIGHT(admin_phone_local, 9);
    admin_email TEXT := 'sy' || admin_phone_no_plus || '@email.com';
    admin_password TEXT := 'changeme123'; -- <-- غيّر كلمة المرور هنا إلى كلمة مرور قوية
    admin_full_name TEXT := 'المدير العام';
    admin_user_id uuid;
BEGIN
    -- Check if the admin user already exists based on the generated email.
    SELECT id INTO admin_user_id FROM auth.users WHERE email = admin_email;

    IF admin_user_id IS NULL THEN
        -- If admin user does not exist, create it.
        INSERT INTO auth.users(id, email, encrypted_password, raw_user_meta_data, email_confirmed_at, aud, role)
        VALUES (
            gen_random_uuid(),
            admin_email,
            crypt(admin_password, gen_salt('bf')),
            jsonb_build_object('full_name', admin_full_name, 'mobile_number', admin_phone_local),
            now(),
            'authenticated',
            'authenticated'
        ) RETURNING id INTO admin_user_id;
    ELSE
        -- If admin user exists, update their password. This is useful for password recovery
        -- or if the setup script is run multiple times with a different password.
        UPDATE auth.users
        SET encrypted_password = crypt(admin_password, gen_salt('bf'))
        WHERE id = admin_user_id;
    END IF;

    -- Insert or update the profile for the admin user, ensuring their role and status are correct.
    INSERT INTO public.profiles (id, full_name, mobile_number, role, is_approved, is_active, subscription_start_date, subscription_end_date)
    VALUES (
        admin_user_id,
        admin_full_name,
        admin_phone_local,
        'admin',
        true,
        true,
        '2024-01-01',
        '2999-12-31'
    )
    ON CONFLICT (id) DO UPDATE SET
        role = EXCLUDED.role,
        is_approved = EXCLUDED.is_approved,
        is_active = EXCLUDED.is_active,
        subscription_start_date = EXCLUDED.subscription_start_date,
        subscription_end_date = EXCLUDED.subscription_end_date,
        full_name = EXCLUDED.full_name,
        mobile_number = EXCLUDED.mobile_number;
END $$;

-- 9. REFRESH SCHEMA CACHE
-- This final command is critical. It forces Supabase's API layer (PostgREST)
-- to reload its internal schema cache, ensuring it recognizes all the newly
-- created tables, columns, and functions immediately. Without this, you might
-- encounter "relation ... does not exist" or "column ... does not exist" errors
-- until the cache refreshes on its own.
NOTIFY pgrst, 'reload schema';
`;

const realtimeScript = `
-- =================================================================
-- سكربت تفعيل المزامنة الفورية (Real-time)
-- =================================================================
-- هذا السكربت يقوم بتفعيل خاصية المزامنة الفورية لجميع جداول البيانات.
-- هذا السكربت آمن للتشغيل عدة مرات، سيقوم فقط بإضافة الجداول غير الموجودة في المزامنة.

DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'profiles', 'assistants', 'clients', 'cases', 'stages', 'sessions', 
        'admin_tasks', 'appointments', 'accounting_entries', 'invoices', 
        'invoice_items', 'site_finances', 'case_documents'
    ]
    LOOP
        -- Add the table to the publication only if it's not already there
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND tablename = table_name AND schemaname = 'public'
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I;', table_name);
        END IF;
    END LOOP;
END$$;
`;

const accountingScript = `
-- =================================================================
-- سكربت إنشاء الجداول المتعلقة بقسم المحاسبة
-- =================================================================
-- هذا السكربت يحتوي على الأوامر اللازمة لإنشاء جداول المحاسبة وسياسات الأمان الخاصة بها.
-- !! هام: هذا السكربت سيقوم بحذف وإعادة إنشاء جداول المحاسبة إذا كانت موجودة !!
-- ملاحظة: يفترض هذا السكربت أن جداول profiles, clients, cases, auth.users موجودة مسبقاً.

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT 'DROP POLICY IF EXISTS "' || policyname || '" ON public.' || tablename || ';' as statement FROM pg_policies WHERE schemaname = 'public' AND tablename IN ('site_finances', 'accounting_entries', 'invoices', 'invoice_items')) LOOP
        EXECUTE r.statement;
    END LOOP;
END$$;

DROP TABLE IF EXISTS public.invoice_items CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.accounting_entries CASCADE;
DROP TABLE IF EXISTS public.site_finances CASCADE;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role INTO user_role FROM public.profiles WHERE id = auth.uid();
    RETURN COALESCE(user_role, 'user') = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;

CREATE TABLE public.site_finances (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, type text DEFAULT 'income' NOT NULL, payment_date date NOT NULL, amount real NOT NULL, description text, payment_method text, category text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.accounting_entries (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, type text NOT NULL, amount real NOT NULL, date timestamptz NOT NULL, description text, client_id text, case_id text, client_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.invoices (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, client_id text NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE, client_name text, case_id text REFERENCES public.cases(id) ON DELETE SET NULL, case_subject text, issue_date timestamptz NOT NULL, due_date timestamptz NOT NULL, tax_rate real DEFAULT 0, discount real DEFAULT 0, status text DEFAULT 'draft', notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.invoice_items (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, invoice_id text NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE, description text NOT NULL, amount real NOT NULL, updated_at timestamptz DEFAULT now());

ALTER TABLE public.site_finances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounting_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable ALL for admin" ON public.site_finances FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Users can select their own site finances" ON public.site_finances FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Enable ALL for own data" ON public.accounting_entries FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable ALL for admin" ON public.accounting_entries FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Enable ALL for own data" ON public.invoices FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable ALL for admin" ON public.invoices FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Enable ALL for own data" ON public.invoice_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable ALL for admin" ON public.invoice_items FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
`;

const repairScript = `
-- =================================================================
-- سكربت إصلاح الأعمدة المفقودة
-- =================================================================
-- هذا السكربت يقوم بإضافة الأعمدة المفقودة إلى الجداول الموجودة دون حذف البيانات.
-- شغله إذا واجهت خطأ "Could not find the '...' column" أو ما شابه.

-- Add 'completed' column to 'appointments' if it doesn't exist.
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT false;

-- Add 'added_at' column to 'case_documents' if it doesn't exist.
ALTER TABLE public.case_documents ADD COLUMN IF NOT EXISTS added_at timestamptz DEFAULT now() NOT NULL;

-- Add 'admin_tasks_layout' column to 'profiles' if it doesn't exist.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS admin_tasks_layout TEXT DEFAULT 'vertical';

-- Remove 'localState' column from 'case_documents' if it was added by mistake.
DO $$
BEGIN
   IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'case_documents' AND column_name = 'localstate'
   ) THEN
      ALTER TABLE public.case_documents DROP COLUMN localstate;
   END IF;
END $$;


-- Force the API schema cache to reload to recognize the changes immediately.
NOTIFY pgrst, 'reload schema';
`;

const rlsRepairScript = `
-- =================================================================
-- سكربت إصلاح خطأ صلاحيات إنشاء الملف الشخصي (RLS)
-- =================================================================
-- هذا السكربت يقوم بإصلاح سياسة الأمان الخاصة بجدول profiles للسماح للمستخدمين الجدد
-- بإنشاء ملفاتهم الشخصية، مما يحل خطأ "violates row-level security policy".

-- RLS Policies for the 'profiles' table (special case).
DROP POLICY IF EXISTS "Users can manage their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can create and manage their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Admins can manage all profiles." ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can view all profiles." ON public.profiles;

CREATE POLICY "Authenticated users can view all profiles." ON public.profiles FOR SELECT
  USING (auth.role() = 'authenticated');
  
CREATE POLICY "Users can create and manage their own profile." ON public.profiles FOR ALL
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Admins can manage all profiles." ON public.profiles FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
  
-- Force the API schema cache to reload to recognize the changes immediately.
NOTIFY pgrst, 'reload schema';
`;

const ScriptDisplay: React.FC<{ script: string }> = ({ script }) => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(script.trim()).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className="relative bg-gray-800 text-white p-4 rounded-md max-h-[40vh] overflow-y-auto">
            <pre className="text-sm whitespace-pre-wrap">
                <code>{script.trim()}</code>
            </pre>
            <button
                onClick={handleCopy}
                className="sticky bottom-2 right-2 flex items-center gap-2 px-3 py-1 bg-gray-600 text-white text-xs rounded-md hover:bg-gray-500"
            >
                {copied ? <ClipboardDocumentCheckIcon className="w-4 h-4 text-green-400"/> : <ClipboardDocumentIcon className="w-4 h-4"/>}
                {copied ? 'تم النسخ' : 'نسخ السكربت'}
            </button>
        </div>
    );
}

const ConfigurationModal: React.FC<{ onRetry: () => void }> = ({ onRetry }) => {
    const [view, setView] = React.useState<'setup' | 'storage' | 'realtime' | 'repair' | 'cors'>('setup');

    return (
        <div className="flex items-center justify-center min-h-screen bg-gray-100 p-4" dir="rtl">
            <div className="w-full max-w-4xl p-8 space-y-6 bg-white rounded-lg shadow-md">
                <div className="text-center">
                    <h1 className="text-3xl font-bold text-gray-800">إعداد قاعدة البيانات</h1>
                     <p className="mt-2 text-gray-600">
                        {view === 'setup' && "يبدو أن قاعدة البيانات غير مهيأة. يرجى اتباع الخطوات التالية لإعداد التطبيق."}
                        {view === 'storage' && "لتمكين مزامنة الوثائق، يجب إعداد مساحة التخزين السحابية (Storage)."}
                        {view === 'realtime' && "استخدم هذا القسم لتفعيل المزامنة الفورية إذا توقفت عن العمل."}
                        {view === 'repair' && "إذا واجهت أخطاء، قد تحتاج لتشغيل سكربت الإصلاح."}
                        {view === 'cors' && "إذا واجهت أخطاء 'Failed to fetch' فهذا يعني أن الخادم يرفض الاتصال من هذا الموقع."}
                    </p>
                </div>

                <div className="border-b border-gray-200">
                    <nav className="-mb-px flex space-x-8 overflow-x-auto" aria-label="Tabs">
                        <button onClick={() => setView('setup')} className={`${view === 'setup' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm`}>الإعداد الكامل</button>
                        <button onClick={() => setView('storage')} className={`${view === 'storage' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm`}>إعداد التخزين</button>
                        <button onClick={() => setView('realtime')} className={`${view === 'realtime' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm`}>المزامنة الفورية</button>
                        <button onClick={() => setView('repair')} className={`${view === 'repair' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm`}>إصلاح الأخطاء</button>
                        <button onClick={() => setView('cors')} className={`${view === 'cors' ? 'border-red-500 text-red-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'} whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm`}>إصلاح أخطاء الشبكة (CORS)</button>
                    </nav>
                </div>

                {view === 'setup' && (
                    <div className="space-y-4 animate-fade-in">
                        <p className="text-sm text-gray-600">السكربت التالي سيقوم بإعداد الجداول والصلاحيات وتفعيل المزامنة الفورية. <strong className="text-red-600">هام:</strong> يجب تعديل بيانات المدير داخل السكربت قبل تشغيله.</p>
                        <ScriptDisplay script={unifiedScript} />
                        <ol className="list-decimal list-inside space-y-2 text-gray-700">
                            <li>اذهب إلى <strong className="font-semibold">SQL Editor</strong> في لوحة تحكم Supabase.</li>
                            <li>الصق السكربت، عدّل بيانات المدير، ثم اضغط <strong className="font-semibold text-green-600">RUN</strong>.</li>
                            <li><strong className="text-red-600">بعد النجاح، انتقل إلى تبويب "إعداد التخزين" لإكمال الإعداد.</strong></li>
                        </ol>
                    </div>
                )}
                
                {view === 'cors' && (
                     <div className="space-y-4 animate-fade-in">
                        <h2 className="text-xl font-semibold text-red-700">حل مشكلة "Failed to fetch"</h2>
                         <p className="text-sm text-gray-600">لأسباب أمنية، يرفض خادم Supabase الاتصالات من مصادر غير معروفة. يجب عليك أن تخبر الخادم صراحةً أن هذا التطبيق مسموح له بالاتصال.</p>
                        <ol className="list-decimal list-inside space-y-3 text-gray-700">
                            <li>اذهب إلى لوحة تحكم مشروعك في Supabase.</li>
                            <li>من القائمة الجانبية، اذهب إلى <strong className="font-semibold">API Settings</strong>.</li>
                            <li>ابحث عن قسم <strong className="font-semibold">CORS settings</strong>.</li>
                            <li>في حقل الإدخال تحت <strong className="font-semibold">Allowed Origins (CORS)</strong>، أدخل الرمز التالي: <code className="bg-gray-200 p-1 rounded">*</code></li>
                            <li>اضغط <strong className="font-semibold">Add</strong> ثم اضغط <strong className="font-semibold text-green-600">Save</strong>.</li>
                        </ol>
                         <div className="p-4 bg-yellow-50 border-l-4 border-yellow-400">
                            <p className="text-yellow-800"><strong className="font-semibold">ملاحظة:</strong> استخدام الرمز <code className="bg-gray-200 p-1 rounded text-sm">*</code> يسمح لأي موقع بالاتصال بقاعدة بياناتك. هذا مناسب للتطوير والاختبار. للبيئات الإنتاجية، يفضل استخدام رابط التطبيق المحدد بدلاً من <code className="bg-gray-200 p-1 rounded text-sm">*</code>.</p>
                        </div>
                    </div>
                )}
                
                {view === 'storage' && (
                    <div className="space-y-4 animate-fade-in">
                        <h2 className="text-xl font-semibold">إعداد مساحة التخزين (Storage) لمزامنة الوثائق</h2>
                         <ol className="list-decimal list-inside space-y-3 text-gray-700">
                            <li>من لوحة تحكم Supabase، اذهب إلى <strong className="font-semibold">Storage</strong>.</li>
                            <li>اضغط على <strong className="font-semibold">Create a new bucket</strong>.</li>
                            <li>أدخل اسم الحاوية (Bucket name): <code className="bg-gray-200 p-1 rounded">documents</code></li>
                            <li><strong className="text-red-600">ألغِ</strong> تحديد خيار <strong className="font-semibold">Public bucket</strong>.</li>
                            <li>اضغط <strong className="font-semibold">Create bucket</strong>.</li>
                            <li>بعد إنشاء الحاوية، اذهب إلى <strong className="font-semibold">Policies</strong>.</li>
                            <li>اضغط <strong className="font-semibold">New Policy</strong> واختر <strong className="font-semibold">"Create a policy from scratch"</strong>.</li>
                            <li>أنشئ 4 سياسات منفصلة (واحدة لكل عملية) للسماح للمستخدمين بقراءة جميع الملفات وإدارة ملفاتهم فقط.</li>
                        </ol>
                        <div className="space-y-4">
                            <div className="p-4 bg-gray-50 border rounded-lg">
                                <p className="font-semibold">1. سياسة عرض الملفات (SELECT):</p>
                                <ul className="list-disc list-inside mt-2 text-sm space-y-1">
                                    <li><strong>Policy Name:</strong> <code className="bg-gray-200 p-1 rounded text-xs">Allow authenticated read access</code></li>
                                    <li><strong>Allowed operation:</strong> <code className="bg-gray-200 p-1 rounded text-xs">SELECT</code></li>
                                    <li><strong>Target roles:</strong> <code className="bg-gray-200 p-1 rounded text-xs">authenticated</code></li>
                                    <li><strong>USING expression (انسخ والصق):</strong></li>
                                </ul>
                                <ScriptDisplay script={`(bucket_id = 'documents')`} />
                            </div>
                             <div className="p-4 bg-gray-50 border rounded-lg">
                                <p className="font-semibold">2. سياسة إضافة وتعديل وحذف الملفات (INSERT, UPDATE, DELETE):</p>
                                <p className="text-sm text-gray-600">أنشئ 3 سياسات منفصلة لهذه العمليات الثلاث، واستخدم نفس الإعدادات التالية في كل منها (غيّر فقط اسم السياسة والعملية المسموحة).</p>
                                <ul className="list-disc list-inside mt-2 text-sm space-y-1">
                                     <li><strong>Policy Name:</strong> اسم وصفي (مثال: <code className="bg-gray-200 p-1 rounded text-xs">Allow user insert own files</code>)</li>
                                    <li><strong>Allowed operation:</strong> اختر العملية (<code className="bg-gray-200 p-1 rounded text-xs">INSERT</code> أو <code className="bg-gray-200 p-1 rounded text-xs">UPDATE</code> أو <code className="bg-gray-200 p-1 rounded text-xs">DELETE</code>)</li>
                                    <li><strong>Target roles:</strong> <code className="bg-gray-200 p-1 rounded text-xs">authenticated</code></li>
                                    <li><strong>USING expression / WITH CHECK expression (انسخ والصق):</strong></li>
                                </ul>
                                <ScriptDisplay script={`(bucket_id = 'documents' AND auth.uid()::text = (storage.foldername(name))[1])`} />
                            </div>
                        </div>
                    </div>
                )}

                {view === 'repair' && (
                    <div className="space-y-6 animate-fade-in">
                        <div className="space-y-4">
                            <h2 className="text-xl font-semibold">إصلاح الأعمدة المفقودة</h2>
                            <p className="text-sm text-gray-600">إذا كنت تواجه خطأً مثل <code className="bg-gray-200 p-1 rounded text-sm">Could not find the '...' column</code>، فهذا يعني أن مخطط قاعدة بياناتك قديم. انسخ وشغّل السكربت التالي في <strong className="font-semibold">SQL Editor</strong> الخاص بـ Supabase لإصلاح المشكلة دون فقدان بياناتك الحالية.</p>
                            <ScriptDisplay script={repairScript} />
                        </div>
                         <div className="space-y-4 border-t pt-6">
                            <h2 className="text-xl font-semibold">إصلاح خطأ صلاحيات إنشاء الملف الشخصي</h2>
                            <p className="text-sm text-gray-600">إذا واجهت خطأ <code className="bg-gray-200 p-1 rounded text-sm">new row violates row-level security policy for table "profiles"</code>، فهذا يعني أن سياسات الأمان تمنع المستخدمين الجدد من إنشاء ملفاتهم الشخصية. انسخ وشغّل هذا السكربت لإصلاح المشكلة.</p>
                            <ScriptDisplay script={rlsRepairScript} />
                        </div>
                    </div>
                )}
                {view === 'realtime' && ( <div className="space-y-4 animate-fade-in"> <h2 className="text-xl font-semibold">تفعيل المزامنة الفورية (Real-time)</h2> <p className="text-sm text-gray-600"> إذا لم تعمل ميزة التحديث الفوري بين المستخدمين، قد تحتاج إلى تشغيل هذا السكربت يدوياً. </p> <ScriptDisplay script={realtimeScript} /> </div> )}

                <div className="text-center border-t pt-6">
                    <p className="text-gray-600 mb-4">بعد التأكد من نجاح تنفيذ الخطوات، اضغط على الزر أدناه لإعادة محاولة الاتصال.</p>
                    <button onClick={onRetry} className="px-8 py-3 text-white bg-blue-600 rounded-lg hover:bg-blue-700 font-semibold">إعادة المحاولة</button>
                </div>
            </div>
        </div>
    );
};

export default ConfigurationModal;